package dev.sonypods.protocol

import java.util.UUID

object SonyGatt {
    private const val UUID_SUFFIX = "-6bc7-4802-8e9a-723ceca4bd8f"

    val BLUETOOTH_IAP_CONNECTION_SERVICE: UUID = service(0x06)
    val BLUETOOTH_IAP_CONNECTION_MC_SERVICE: UUID = service(0x0A)
    val BLE_PAIRING_TWS_HPC_SERVICE: UUID = service(0x0D)
    val TANDEM_V2_HPC_SERVICE: UUID = service(0x20)
    val TANDEM_V2_MC_SERVICE: UUID = service(0x21)
    val TANDEM_V1_MC_SERVICE: UUID = service(0x23)
    val TANDEM_SSH_SERVICE: UUID = service(0x25)
    val BLUETOOTH_PAIRING_COMPLETE_NAME_SERVICE: UUID = service(0x26)
    val LE_AUDIO_CAPABILITY_FOR_HPC: UUID = service(0x27)
    val BLUETOOTH_CONNECTION: UUID = characteristic(0x10)
    val BLUETOOTH_MODE: UUID = characteristic(0x11)
    val BLUETOOTH_CONNECTION_STATUS: UUID = characteristic(0x12)
    val BLUETOOTH_MODE_STATUS: UUID = characteristic(0x13)
    val LE_AD_PACKET_IDENTIFIER: UUID = characteristic(0x17)
    val LE_AD_PACKET_IDENTIFIER_LEFT: UUID = characteristic(0x18)
    val LE_AD_PACKET_IDENTIFIER_RIGHT: UUID = characteristic(0x19)
    val TARGET_ANNOUNCEMENT_LE_AD: UUID = characteristic(0x1A)
    val COMPLETE_BLUETOOTH_FRIENDLY_NAME: UUID = characteristic(0x1B)
    val SYNC_BLUETOOTH_FRIENDLY_NAME_INDEX: UUID = characteristic(0x1C)
    val BLUETOOTH_PUBLIC_ADDRESS: UUID = characteristic(0x1D)
    val TANDEM_HPC_TO_ACC: UUID = characteristic(0x60)
    val TANDEM_HPC_FROM_ACC: UUID = characteristic(0x61)
    val TANDEM_MC_TO_ACC: UUID = characteristic(0x62)
    val TANDEM_MC_FROM_ACC: UUID = characteristic(0x63)
    val LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY: UUID = characteristic(0x68)
    val READY_TO_START_INITIAL_COMMUNICATION: UUID = characteristic(0x90)
    val WRITABLE_VALUE_LENGTH: UUID = characteristic(0x91)
    val DETERMINE_MTU: UUID = characteristic(0x93)
    val OPTIMAL_MTU: UUID = characteristic(0x94)

    fun service(suffix: Int): UUID = UUID.fromString("5b833e%02x$UUID_SUFFIX".format(suffix))

    fun characteristic(suffix: Int): UUID = UUID.fromString("5b833c%02x$UUID_SUFFIX".format(suffix))

    fun serviceLabel(uuid: UUID): String = when (uuid) {
        BLUETOOTH_IAP_CONNECTION_SERVICE -> "BLUETOOTH_IAP_CONNECTION_SERVICE"
        BLUETOOTH_IAP_CONNECTION_MC_SERVICE -> "BLUETOOTH_IAP_CONNECTION_MC_SERVICE"
        BLE_PAIRING_TWS_HPC_SERVICE -> "BLE_PAIRING_TWS_HPC_SERVICE"
        TANDEM_V2_HPC_SERVICE -> "TANDEM_V2_HPC_SERVICE"
        TANDEM_V2_MC_SERVICE -> "TANDEM_V2_MC_SERVICE"
        TANDEM_V1_MC_SERVICE -> "TANDEM_V1_MC_SERVICE"
        TANDEM_SSH_SERVICE -> "TANDEM_SSH_SERVICE"
        BLUETOOTH_PAIRING_COMPLETE_NAME_SERVICE -> "BLUETOOTH_PAIRING_COMPLETE_NAME_SERVICE"
        LE_AUDIO_CAPABILITY_FOR_HPC -> "LE_AUDIO_CAPABILITY_FOR_HPC"
        else -> uuid.toString()
    }

    fun characteristicLabel(uuid: UUID): String = when (uuid) {
        BLUETOOTH_CONNECTION -> "BLUETOOTH_CONNECTION"
        BLUETOOTH_MODE -> "BLUETOOTH_MODE"
        BLUETOOTH_CONNECTION_STATUS -> "BLUETOOTH_CONNECTION_STATUS"
        BLUETOOTH_MODE_STATUS -> "BLUETOOTH_MODE_STATUS"
        LE_AD_PACKET_IDENTIFIER -> "LE_AD_PACKET_IDENTIFIER"
        LE_AD_PACKET_IDENTIFIER_LEFT -> "LE_AD_PACKET_IDENTIFIER_LEFT"
        LE_AD_PACKET_IDENTIFIER_RIGHT -> "LE_AD_PACKET_IDENTIFIER_RIGHT"
        TARGET_ANNOUNCEMENT_LE_AD -> "TARGET_ANNOUNCEMENT_LE_AD"
        COMPLETE_BLUETOOTH_FRIENDLY_NAME -> "COMPLETE_BLUETOOTH_FRIENDLY_NAME"
        SYNC_BLUETOOTH_FRIENDLY_NAME_INDEX -> "SYNC_BLUETOOTH_FRIENDLY_NAME_INDEX"
        BLUETOOTH_PUBLIC_ADDRESS -> "BLUETOOTH_PUBLIC_ADDRESS"
        TANDEM_HPC_TO_ACC -> "TANDEM_HPC_TO_ACC"
        TANDEM_HPC_FROM_ACC -> "TANDEM_HPC_FROM_ACC"
        TANDEM_MC_TO_ACC -> "TANDEM_MC_TO_ACC"
        TANDEM_MC_FROM_ACC -> "TANDEM_MC_FROM_ACC"
        LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY -> "LE_AUDIO_SWITCH_SUPPORTED_COMPATIBILITY"
        READY_TO_START_INITIAL_COMMUNICATION -> "READY_TO_START_INITIAL_COMMUNICATION"
        WRITABLE_VALUE_LENGTH -> "WRITABLE_VALUE_LENGTH"
        DETERMINE_MTU -> "DETERMINE_MTU"
        OPTIMAL_MTU -> "OPTIMAL_MTU"
        else -> uuid.toString()
    }
}
